version: "3.9"
services:
  minecraft:
    build: .
    ports:
      - "25565:25565"
    volumes:
      - /home/minecraft/world/casual:/home/server/world
      - type: bind
        source: /home/minecraft/properties/casual/server.properties
        target: /home/server/server.properties
        read_only: false
