version: "3.9"
services:
  minecraft:
    build: .
    ports:
      - "25565:25565"
    volumes:
      - /home/server/world/casual:/home/server/world
      - /home/server/logs/casual:/home/server/world
      - type: bind
        source: /home/server/properties/casual/server.properties
        target: /home/server/server.properties
        read_only: false
      - type: bind
        source: /home/server/properties/casual/usercache.json
        target: /home/server/usercache.json
        read_only: false
      - type: bind
        source: /home/server/properties/casual/ops.json
        target: /home/server/ops.json
        read_only: false
      - type: bind
        source: /home/server/properties/casual/banned-ips.json
        target: /home/server/banned-ips.json
        read_only: false
      - type: bind
        source: /home/server/properties/casual/banned-players.json
        target: /home/server/banned-players.json
        read_only: false
      - type: bind
        source: /home/server/properties/casual/whitelist.json
        target: /home/server/whitelist.json
        read_only: false
        
