version: "3.9"
services:
  minecraft_spigot:
    build: ./spigot/
    ports:
        - "25565:25565"
    volumes:
      - ./storage/spigot/world/casual:/home/server/world
      - ./storage/spigot/logs/casual:/home/server/world
      - type: bind
        source: ./storage/spigot/properties/casual/server.properties
        target: /home/server/server.properties
        read_only: false
      - type: bind
        source: ./storage/spigot/properties/casual/usercache.json
        target: /home/server/usercache.json
        read_only: false
      - type: bind
        source: ./storage/spigot/properties/casual/ops.json
        target: /home/server/ops.json
        read_only: false
      - type: bind
        source: ./storage/spigot/properties/casual/banned-ips.json
        target: /home/server/banned-ips.json
        read_only: false
      - type: bind
        source: ./storage/spigot/properties/casual/banned-players.json
        target: /home/server/banned-players.json
        read_only: false
      - type: bind
        source: ./storage/spigot/properties/casual/whitelist.json
        target: /home/server/whitelist.json
        read_only: false

  minecraft_vanilla:
    build: ./vanilla/
    ports:
      - "25565:25565"
    volumes:
      - ./storage/vanilla/world/casual:/home/server/world
      - ./storage/vanilla/logs/casual:/home/server/world
      - type: bind
        source: ./storage/vanilla/properties/casual/server.properties
        target: /home/server/server.properties
        read_only: false
      - type: bind
        source: ./storage/vanilla/properties/casual/usercache.json
        target: /home/server/usercache.json
        read_only: false
      - type: bind
        source: ./storage/vanilla/properties/casual/ops.json
        target: /home/server/ops.json
        read_only: false
      - type: bind
        source: ./storage/vanilla/properties/casual/banned-ips.json
        target: /home/server/banned-ips.json
        read_only: false
      - type: bind
        source: ./storage/vanilla/properties/casual/banned-players.json
        target: /home/server/banned-players.json
        read_only: false
      - type: bind
        source: ./storage/vanilla/properties/casual/whitelist.json
        target: /home/server/whitelist.json
        read_only: false
